version: '2'

volumes:
  prom-data:

services:
  app:
    image: sample 
    build: .
    # --reload is usefull for dev purposes.
    # command: ["gunicorn","--reload","-c","gunicorn.py","app:app"]
    command: ["python","app.py"]
    environment:
     - SERVER_PORT:5000
    ports:
     - 5000:5000
    volumes:
    #Mount the source in the folder is useful for dev purposes.
     - ./src:/usr/src/code

  prometheus:
    image: prom/prometheus:v2.4.3
    entrypoint: ["/bin/prometheus"]
    command:
     - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
     - prom-data:/data
     - ./k8s/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
    - 9090:9090

