# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-11 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('enterprise_id', models.IntegerField()),
                ('currency', models.CharField(choices=[(0, 'us_dollar'), (1, 'br_real')], default=0, max_length=1)),
            ],
        ),
    ]
